Add some more tensor docs
DiffSharp/DiffSharp pull request #181
Opened 2020-09-10 18:12 UTC by dsyme

Starting to populate docs in Tensor.fs

Also testing that math can be embedded in docs (see `arange` docs)

There are some issues with cross-references, I'll work on those tomorrow, also will do https://github.com/fsprojects/FSharp.Formatting/issues/604

2020-09-10 19:49 UTC, kevmal requested changes

2020-09-10 19:49 UTC, kevmal commented on src/DiffSharp.Core/Tensor.fs
> +    /// A debugging routine to compute the parents of a tensor involved in reverse-mode autmoatic differentiation
```suggestion
    /// A debugging routine to compute the parents of a tensor involved in reverse-mode automatic differentiation

```

2020-09-10 19:49 UTC, kevmal commented on src/DiffSharp.Core/Tensor.fs
> +    /// Returns a new tensor filled with '1' values for the given shape, element type and configuration, defaulting to the
```suggestion
    /// Returns a new tensor filled with '0' values for the given shape, element type and configuration, defaulting to the 

```

2020-09-10 19:49 UTC, kevmal commented on src/DiffSharp.Core/Tensor.fs
> +    /// Returns a new tensor with random values drawn from the normal distribution, for the
```suggestion
    /// Returns a new tensor with random values drawn from the standard normal distribution, for the

```

2020-09-11 17:13 UTC, dsyme commented
@kevmal Thanks for the proof reading!

2020-09-11 17:14 UTC, dsyme commented
The codecov on the patch failed but it's only documentation, so will merge

2020-09-11 17:14 UTC, merged